---HOW MANY USERS ARE DISABLED and ENABLED

SELECT		[enable], COUNT ([enable])
FROM		[dbo].[UserInfo]
GROUP BY	[enable]

--- LIST OF DISABLED USERS
SELECT		ID, NAME, ENABLE
FROM		[dbo].[UserInfo]
WHERE		ENABLE=0

--- LIST OF ENABLED USERS
SELECT		ID, NAME, ENABLE
FROM		[dbo].[UserInfo]
WHERE		ENABLE=1